let tell1=document.getElementById("tell1")
let tell2=document.getElementById("tell2")
let tell3=document.getElementById("tell3")
let tell4=document.getElementById("tell4")
let tell5=document.getElementById("tell5")
let tell6=document.getElementById("tell6")
tell2.classList.add("telname")
tell3.classList.add("telname")
tell4.classList.add("telname")
tell5.classList.add("telname")
tell6.classList.add("telname")
tell1.classList.add("name")
